# Generated by Django 5.1.2 on 2024-10-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_acbunit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acbunit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='acbunit',
            name='energy_consumption',
        ),
        migrations.RemoveField(
            model_name='acbunit',
            name='temperature',
        ),
        migrations.CreateModel(
            name='UnitConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_consumption', models.FloatField()),
                ('temperature', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption', to='units.acbunit')),
            ],
        ),
    ]
